### ISSUE TITLE
API error (autobuy)

### ISSUE THREAD

**Issue by Thomasjee** [ewkt/Vinted-Discord-Notifications#12]
making an authed request to https://www.vinted.nl/api/v2/conversations
TypeError: Cannot read properties of undefined (reading 'transaction')
    at getTransactionId (file:///home/username/Vinted-Discord-Notifications/src/bot/buy.js:31:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async autobuy (file:///home/username/Vinted-Discord-Notifications/src/bot/buy.js:102:31)

**Comment by ewkt** [comment]
hi yes this is a known issue sorry, the request isnt being authenticated properly

**Comment by Kezzow** [comment]
Now you need to have access to a Vinted developer to have some sort of API to be able to run the bot. That's what I understood.

**Comment by ewkt** [comment]
actually everything still works fine to navigate the API with a token that has user privileges (so u need to be logged in and your scrapping activity is linked to you)

**Comment by ewkt** [comment]
branch autobuy fixes this issues
